title: <p align="center"> Aswin Govindan </p>

logo: "/logo/circle_headshot.png"

description:
  <p align="center">
  <a href=" https://www.linkedin.com/in/aswinram789/">LinkedIn</a> |
  <a href="https://github.com/aswinram1997">GitHub</a>
  </p>
  
theme: jekyll-theme-minimal
