title: <p align="center"> Aswin Govindan </p>

logo: "/logo/circle_headshot.png"

description:
  <p align="center">
  <a href=" https://www.linkedin.com/in/aswinram789/">LinkedIn</a> |
  <a href="https://github.com/aswinram1997">GitHub</a>
  </p>

  <p align="justify">
  I am a driven data scientist working at Landmark Homes and pursuing a PhD in Engineering Management at the University of Alberta. With a deep-rooted passion for data science, I am driven to address a wide range of real-world challenges. By leveraging my technical expertise, research acumen, and business acumen, I am determined to develop and implement transformative solutions that make a significant impact.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal

