title: <p align="center"> Aswin Govindan </p>

logo: "/logo/circle_headshot.png"

description:
  <p align="center">
  <a href=" https://www.linkedin.com/in/aswinram789/">LinkedIn</a> |
  <a href="https://github.com/aswinram1997">GitHub</a>
  </p>

  <p align="justify">
I strive to revolutionize industries and drive transformative change by bridging Science and Business as a passionate Data Scientist and Researcher.
  </p>
  
theme: jekyll-theme-minimal

