title: <p align="center"> Aswin Govindan </p>

logo: "/logo/circle_headshot.png"

description:
  <p align="center">
  <a href=" https://www.linkedin.com/in/aswinram789/">LinkedIn</a> |
  <a href="https://github.com/aswinram1997">GitHub</a>
  </p>

  <p align="justify">
 Igniting transformation through data-driven solutions, I bridge Science and Business with unwavering curiosity and innovation as a Ph.D. candidate in Engineering Management and passionate data scientist at Landmark Homes.
  </p>
  
theme: jekyll-theme-minimal

