title: <p align="center"> Aswin Govindan </p>

logo: "/logo/circle_headshot.png"

description:
  <p align="center">
  <a href=" https://www.linkedin.com/in/aswinram789/">LinkedIn</a> |
  <a href="https://github.com/aswinram1997">GitHub</a>
  </p>

  <p align="justify">
 Welcome to my Git Page! I'm a passionate data scientist at Landmark Homes and a Ph.D. candidate in Engineering Management at the University of Alberta. With honed technical and research skills, I develop transformative solutions for real-world challenges. Bridging the gap between Science and Business, I fuel change through curiosity and innovation. 
  </p>
  
theme: jekyll-theme-minimal

